### ISSUE TITLE
Suggestion: publish to clojars

### ISSUE THREAD

**Issue by davidpham87** [yogthos/hiccup-template#1]
Hello,

I find this library would be a fine addition to clojars, (especially since now Selmer belongs to babashka).

Do you think it would make sense to publish in Clojars and make it available to Clojure as well?

Best regards,
David

**Comment by yogthos** [comment]
Oh good idea, just pushed it to Clojars as `[net.clojars.yogthos/hiccup-template "0.1.2"]`.
